"""add_answer_mode_to_messages

Revision ID: 52b64a8bbaec
Revises: 199bc8d97f38
Create Date: 2026-07-16 22:52:05.106888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b64a8bbaec'
down_revision: Union[str, None] = '199bc8d97f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('answer_mode', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'answer_mode')
    # ### end Alembic commands ###
