"""Add FileView and SearchHistory source

Revision ID: 8917ba1012ee
Revises: 575594fb3f1e
Create Date: 2026-07-20 23:44:22.186965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8917ba1012ee'
down_revision: Union[str, None] = '575594fb3f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'file_id', name='uq_file_view_user_file')
    )
    op.create_index(op.f('ix_file_views_file_id'), 'file_views', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_views_user_id'), 'file_views', ['user_id'], unique=False)
    op.execute("DROP INDEX IF EXISTS chunks_embedding_ivfflat_idx")
    op.add_column('search_history', sa.Column('source', sa.String(length=20), server_default='search', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'source')
    op.create_index('chunks_embedding_ivfflat_idx', 'chunks', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_file_views_user_id'), table_name='file_views')
    op.drop_index(op.f('ix_file_views_file_id'), table_name='file_views')
    op.drop_table('file_views')
    # ### end Alembic commands ###
