"""add_oauth_columns

Revision ID: af90878068d5
Revises: 8dbd55961539
Create Date: 2026-07-15 21:15:24.232033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af90878068d5'
down_revision: Union[str, None] = '8dbd55961539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the ENUM type object first
    oauth_provider_enum = sa.Enum('local', 'google', 'github', name='oauthprovider')
    oauth_provider_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.Enum('local', 'google', 'github', name='oauthprovider'), server_default='local', nullable=False))
    op.add_column('users', sa.Column('oauth_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint('uq_user_oauth_provider_id', 'users', ['oauth_provider', 'oauth_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_oauth_provider_id', 'users', type_='unique')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'oauth_id')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###

    # Drop the ENUM type
    oauth_provider_enum = sa.Enum('local', 'google', 'github', name='oauthprovider')
    oauth_provider_enum.drop(op.get_bind(), checkfirst=True)
